import { store } from '../data/store.js';

function generateId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

export function startStockCheckTimer(): NodeJS.Timeout {
  console.log('[StockCheckTimer] Starting stock check timer (every 30s)');

  return setInterval(() => {
    const data = store.getData();
    const stocks = data.materialStocks;
    const now = new Date();

    stocks.forEach((stock) => {
      if (stock.currentStock > stock.minStock) return;

      const recentPR = data.purchaseRequests.find(
        (p) =>
          (p.triggeredByMaterialId === stock.id || p.items.some((it) => it.materialId === stock.id)) &&
          (p.status === 'submitted' || p.status === 'first_approved' || p.status === 'draft')
      );
      if (recentPR) return;

      const shortage = stock.maxStock * 0.7 - stock.currentStock;
      const orderQty = Math.max(
        Math.ceil(stock.minStock * 2),
        Math.ceil(shortage > 0 ? shortage : stock.minStock)
      );

      const urgency: 'low' | 'medium' | 'high' =
        stock.currentStock <= stock.minStock * 0.3
          ? 'high'
          : stock.currentStock <= stock.minStock * 0.6
          ? 'medium'
          : 'low';

      const users = data.users;
      const systemUser = users.find((u) => u.role === 'hq_admin') || users[0];
      const drillingEngineer = users.find((u) => u.role === 'drilling_engineer');
      const requestedBy = (drillingEngineer || systemUser).id;

      const totalAmount = Math.round(orderQty * stock.unitPrice * 100) / 100;

      const next = data.purchaseRequests.length + 1;
      const pr = {
        id: generateId(),
        code: `PR-AUTO-${String(next).padStart(4, '0')}`,
        title: `[自动采购] ${stock.name} 库存不足 (当前:${stock.currentStock}${stock.unit}, 安全线:${stock.minStock}${stock.unit})`,
        requestedBy,
        department: 'drilling',
        status: 'submitted' as const,
        autoGenerated: true,
        triggeredByMaterialId: stock.id,
        triggeredByStockLevel: stock.currentStock,
        totalAmount,
        items: [
          {
            materialId: stock.id,
            materialName: stock.name,
            quantity: orderQty,
            unitPrice: stock.unitPrice,
          },
        ],
        urgency,
        expectedDeliveryDate: new Date(now.getTime() + (urgency === 'high' ? 3 : urgency === 'medium' ? 7 : 14) * 86400000).toISOString(),
        notes: `系统自动生成采购申请：${stock.name} 库存低于安全线。当前库存:${stock.currentStock}${stock.unit}, 最低安全库存:${stock.minStock}${stock.unit}。建议采购数量:${orderQty}${stock.unit}。`,
        createdAt: now.toISOString(),
        updatedAt: now.toISOString(),
      };

      data.purchaseRequests.push(pr);

      console.log(
        `[StockCheckTimer] Low stock alert for ${stock.code} (${stock.name}): ` +
          `current=${stock.currentStock}${stock.unit}, min=${stock.minStock}${stock.unit}, ` +
          `auto-created purchase request ${pr.code}, urgency=${urgency}, qty=${orderQty}`
      );
    });
  }, 30000);
}
